# Generated by Django 5.2.5 on 2025-09-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('ambulanceid', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('equipment_level', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], max_length=10)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('on_call', 'On Call'), ('maintenance', 'Maintenance')], default='available', max_length=15)),
            ],
        ),
    ]
