# Generated by Django 5.2.5 on 2025-09-08 06:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.ambulance'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='hospital_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='request_type',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('normal', 'Normal')], default='emergency', max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
