# Generated by Django 5.2.5 on 2025-09-04 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='ambulance_lat',
            field=models.FloatField(default=24.8607),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='ambulance_lng',
            field=models.FloatField(default=67.0011),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='eta_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.driver'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambulance.emergencyrequest'),
        ),
    ]
