# Generated by Django 5.2.5 on 2025-09-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_dispatch_ambulance_lat_dispatch_ambulance_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambulance.driver'),
        ),
    ]
