# Generated by Django 5.2.5 on 2025-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0003_emergencyrequest_user_dispatch_emergencyrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='emergency_type',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
