# Generated by Django 5.2.5 on 2025-09-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0004_emergencyrequest_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='emergency_type',
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='description',
            field=models.TextField(),
        ),
    ]
