# Generated by Django 5.2.5 on 2025-09-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0005_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
